- name: Nginx installation
  hosts: all
  become: yes
  tasks:  
    - name: Update apt-get repo and cache
      ansible.builtin.apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600
    - name: Install nginx
      ansible.builtin.apt: 
        name: "{{item}}"
        state: present
      loop: 
      - ca-certificates
      - curl
      - gnupg
    - name: add GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present 
    - name: add docker repository to apt
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Update apt-cache
      ansible.builtin.apt: 
        update_cache: yes 
    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    
